"""empty message

Revision ID: d260b19c5598
Revises: d6f069ba9bdf
Create Date: 2026-02-24 15:25:28.248377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd260b19c5598'
down_revision: Union[str, Sequence[str], None] = 'd6f069ba9bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('language', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'language')
    # ### end Alembic commands ###
