"""empty message

Revision ID: d6f069ba9bdf
Revises:
Create Date: 2026-02-23 18:57:27.107768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f069ba9bdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'guilds',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('prefix', sa.String(), nullable=False),
        sa.Column('is_premium', sa.Boolean(), nullable=False),
        sa.Column('premium_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'appeal_settings',
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
        sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('schema_version', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint('schema_version > 1', name='ck_schema_version_is_positive'),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('guild_id'),
    )
    op.create_table(
        'case_logs',
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('target_id', sa.BigInteger(), nullable=False),
        sa.Column('moderator_id', sa.BigInteger(), nullable=False),
        sa.Column(
            'action_type',
            sa.Enum('ban', 'kick', 'mute', 'warn', name='actiontype'),
            nullable=False,
        ),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'duration is NULL or duration >= 0', name='cx_duration_seconds_is_positive'
        ),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('case_id'),
    )
    op.create_index('ix_case_logs_guild_id', 'case_logs', ['guild_id'], unique=False)
    op.create_index('ix_case_logs_mod_id', 'case_logs', ['moderator_id'], unique=False)
    op.create_index('ix_case_logs_target_id', 'case_logs', ['target_id'], unique=False)
    op.create_table(
        'mod_settings',
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('is_dm_enabled', sa.Boolean(), nullable=False),
        sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
        sa.Column('reason_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('guild_id'),
    )
    op.create_table(
        'appeal_logs',
        sa.Column('appeal_id', sa.Integer(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('pending', 'approved', 'declined', name='appealstatus'),
            nullable=False,
        ),
        sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
        sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['case_id'], ['case_logs.case_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('appeal_id'),
    )
    op.create_index('ix_appeal_logs_guild_id', 'appeal_logs', ['guild_id'], unique=False)
    op.create_table(
        'case_edits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('case_id', sa.Integer(), nullable=False),
        sa.Column('old_reason', sa.String(), nullable=True),
        sa.Column('new_reason', sa.String(), nullable=True),
        sa.Column('edited_by', sa.BigInteger(), nullable=False),
        sa.Column('edited_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['case_id'], ['case_logs.case_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_case_edits_case_id', 'case_edits', ['case_id'], unique=False)
    op.create_index('ix_case_edits_mod_id', 'case_edits', ['edited_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_edits_mod_id', table_name='case_edits')
    op.drop_index('ix_case_edits_case_id', table_name='case_edits')
    op.drop_table('case_edits')
    op.drop_index('ix_appeal_logs_guild_id', table_name='appeal_logs')
    op.drop_table('appeal_logs')
    op.drop_table('mod_settings')
    op.drop_index('ix_case_logs_target_id', table_name='case_logs')
    op.drop_index('ix_case_logs_mod_id', table_name='case_logs')
    op.drop_index('ix_case_logs_guild_id', table_name='case_logs')
    op.drop_table('case_logs')
    op.drop_table('appeal_settings')
    op.drop_table('guilds')
    # ### end Alembic commands ###
